---
- name: Include "{{ansible_os_family}}" SGE recipe
  include: "{{ansible_os_family}}.yaml"

- name: Change ec3-cloud-users project
  lineinfile:
    path: /etc/ec3-cloud-users/config.conf
    regexp: '^project = '
    line: project = {{project}}

- name: Change ec3-cloud-users home path
  lineinfile:
    path: /etc/ec3-cloud-users/config.conf
    regexp: '^homeprefix = '
    line: homeprefix = {{homeprefix}}

- name: Change ec3-cloud-users ip
  lineinfile:
    path: /etc/ec3-cloud-users/config.conf
    regexp: '^ipaddress = '
    line: ipaddress = {{ hostvars[groups["front"][0]]["IM_NODE_PUBLIC_IP"] }}

- name: Include "{{sge_type_of_node}}" SGE recipe
  include: "{{sge_type_of_node}}.yaml"

- name: Start ec3-cloud-users script
  shell: /usr/libexec/ec3-cloud-users/sync-feed.py; /usr/libexec/ec3-cloud-users/create-accounts.py
